### ISSUE TITLE
[Suggestion] Make it clearer/more user friendly on how to disable caching

### ISSUE THREAD

**Issue by Rings4** [gittromney/Playnite-NowPlaying#15]
Just a small suggestion I thought I'd make given how much I like and admire this plugin.

Currently, to disable caching for a game, you have to "Uninstall" it. If you don't remember the docs/instructions for this plugin, you wouldn't think to click "Uninstall" in order to disable caching.

1. I think you should add the plugin's logo in front of the "Uninstall" option, and maybe even rename that option to "Uninstall from cache" or similar, so it's clear that this is the setting you need to click in order to disable caching.

2. Perhaps even combine uninstalling and disabling the cache for this game into the same step, so instead of an Install button, you'll have the Play button back after uninstalling.

If you make these settings that you can toggle, I suggest at least making suggestion 1 the default setting as it seems most intuitive.

Thank you again for this great plugin! This is literally a game changer (pun intended).

**Comment by gittromney** [comment]
Hi, good suggestions - I'll look into the possibility of doing both 1 + 2, and I'm glad you are enjoying the plugin.

One thing to keep in mind is that there might be different use cases for game caching.  As an example, one approach could be where just before playing a game you ENABLE caching + INSTALL it (create its cache); then after finishing it you UNINSTALL it (delete its cache) + DISABLE game caching for it.

An alternative approach, and my recommendation,  would be instead to ENABLE all of your eligible games for caching at once (remember, doing this does not actually create any game caches, it just makes changes to those game(s) so that they appear to Playnite as coming from a Library.)  Then whenever you play any of those games, you will just do INSTALL + PLAY + UNINSTALL.  The INSTALL step will actually create the game cache(s) on your NVMe/SSD, and UNINSTALL will delete the cache(s) to free up disk space.  In this use case I wouldn't recommend ever DISABLING caching for your games (unless you needed to do so for some other reason).

Hopefully that explanation makes sense.
________________________________
From: Rings4 ***@***.***>
Sent: Monday, August 12, 2024 1:33 PM
To: gittromney/Playnite-NowPlaying ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gittromney/Playnite-NowPlaying] [Suggestion] Make it clearer/more user friendly on how to disable caching (Issue #15)


Just a small suggestion I thought I'd make given how much I like and admire this plugin.

Currently, to disable caching for a game, you have to "Uninstall" it. If you don't remember the docs/instructions for this plugin, you wouldn't think to click "Uninstall" in order to disable caching.

  1.  I think you should add the plugin's logo in front of the "Uninstall" option, and maybe even rename that option to "Uninstall from cache" or similar, so it's clear that this is the setting you need to click in order to disable caching.

  2.  Perhaps even combine uninstalling and removing from the cache into the same step.

If you make these settings that you can toggle, I suggest at least making suggestion 1 the default setting as it seems most intuitive.

Thank you again for this great plugin! This is literally a game changer (pun intended).

**Comment by Rings4** [comment]
That explanation makes perfect sense! That's why I think adding my suggestions as settings as opposed to outright changing the behaviour of the plugin would be great, as it would conform to the person's needs. 

Currently, I don't see myself wanting to set up caching for my games in bulk to then install, play, uninstall. Instead, I want to be able to switch caching on when I find that I'm playing a game that's stored on an HDD often enough to justify the SSD space. But, I'm sure in the future, I'll have a slightly different setup and use it the way you describe. I might end up installing an additional internal HDD solely for that purpose.

**Comment by gittromney** [comment]
Please see the latest release (v1.3.5), which at least in part addresses your suggestions.

For item 2. there's now an optional "Uninstall + Disable" command that will show up under the Playnite right-mouse menu when the selected game(s) have their game cache(s) Installed (and when Settings->General->"Show 'Uninstall cache + Disable caching...' is checked).  Note that, by default, this setting is unchecked.

For item 1, unfortunately, I don't see any way of adding Icons or changing text of Playnite's built-in game menu items (like Install/Uninstall/Play).  But, as a work-around, I added optional NowPlaying status/menu tips information to the Playnite right-mouse game menu. Again, this option will need to be enabled, as it is disabled by default.  (See Settings->General->"Show status/menu tips...")

Please try it out and let me know what you think.  Hopefully, the new features are pretty self-explanatory.  
--g

**Comment by gittromney** [comment]
Here are some examples, with both optional features enabled.  In case it's not clear, the menu items with a light grey/monochrome logo are informational only - they don't have any "action" or "command" associated with them.  

Game with cache uninstalled:
![Screenshot 2024-08-30 163712](https://github.com/user-attachments/assets/2a4908ec-9887-497c-a8a5-5e02d147c35f)

Game with cache installed:
![Screenshot 2024-08-30 163959](https://github.com/user-attachments/assets/efe69026-49d4-4bc1-92b2-88b4dcf39107)

Ineligible game selected:
![Screenshot 2024-08-30 164109](https://github.com/user-attachments/assets/bf40fa4e-5359-4d19-8083-796df192514b)

A variety of games selected:
![Screenshot 2024-08-30 164451](https://github.com/user-attachments/assets/3d88c398-cabc-4a34-a66d-8951abbb69a0)

Also, with this release (v.1.3.5), you can now install multiple caches at once (staged in a queue, the same as if done from the NowPlaying sidepanel view):
![Screenshot 2024-08-30 164834](https://github.com/user-attachments/assets/5168b03f-f97d-48d7-b149-b026675ca563)

Same goes for uninstalling caches (or 'Uninstalling + Disabling'):
![Screenshot 2024-08-30 164945](https://github.com/user-attachments/assets/e706694a-2100-41c3-8c29-0af1627dc98a)

**Comment by Rings4** [comment]
Absolutely wonderful, thank you very much for implementing my suggestions!
